
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://agedsdeitqgkavqqoldg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFnZWRzZGVpdHFna2F2cXFvbGRnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc5ODY3NTcsImV4cCI6MjA2MzU2Mjc1N30.yf2x_qzccUO4sk-H7YrxFemuEJeFDE8uhCSqUWSonac";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
